http:
  enabled: false

input:
  generate:
    mapping: |
      root = {"name":"John", "toys": ["car", "phone", "cards"], "good": true}
    count: 1

pipeline:
  processors:
    - gotmpl:
        template: >
          Hi there {{ .name }}! Your toys are:
          {{ range .toys }}
            - {{ . -}}
          {{ end }}
          {{ if .good }}
          
          You have been a good boy!
          {{ end }}
